### ISSUE TITLE
BUG? works with python 2.6, but breaks in 2.7

### ISSUE THREAD

**Issue by psych0d0g** [DiffSK/configobj#60]
On debian wheezy it works fine with python 2.6.
if i switch to 2.7 (which is default on wheezy) i get this stacktrace:

```
Unhandled exception: 'module' object has no attribute 'PY2'traceback: Traceback (most recent call last):

  File "/usr/bin/diamond", line 118, in main
    config = configobj.ConfigObj(os.path.abspath(options.configfile))
  File "/usr/local/lib/python2.7/dist-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/local/lib/python2.7/dist-packages/configobj.py", line 1287, in _load
    content = self._handle_bom(content)
  File "/usr/local/lib/python2.7/dist-packages/configobj.py", line 1477, in _handle_bom
    if six.PY2 and isinstance(line, str):
AttributeError: 'module' object has no attribute 'PY2'
```

```
$ python2.7 -c "import configobj; print configobj.__version__"
5.0.5
```

```
$ python2.6 -c "import configobj; print configobj.__version__"
4.7.2
```
